name: Publish dart_test to pub.dev

on:
  push:
    tags:
      - 'luoyi_dart_test-v*'

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Publish
        run: dart pub publish --force
        working-directory: packages/luoyi_dart_test
